//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASCOM.LunaticAstroEQ.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASCOM.LunaticAstroEQ.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{0:0}}:{{1:0}}:{{2:f{0}}}.
        /// </summary>
        internal static string AngleInCadDegreesMinutesSeconds {
            get {
                return ResourceManager.GetString("AngleInCadDegreesMinutesSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{0:f{0}}}°.
        /// </summary>
        internal static string AngleInDecimalDegrees {
            get {
                return ResourceManager.GetString("AngleInDecimalDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{0:f{0}}}°.
        /// </summary>
        internal static string AngleInDecimalDegreesPlusMinus {
            get {
                return ResourceManager.GetString("AngleInDecimalDegreesPlusMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{0:f{0}}}° {{1}}.
        /// </summary>
        internal static string AngleInDecimalDegreesWestEast {
            get {
                return ResourceManager.GetString("AngleInDecimalDegreesWestEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{0:0}}° {{1:f{0}}}&apos;.
        /// </summary>
        internal static string AngleInDegreesDecimalMinutes {
            get {
                return ResourceManager.GetString("AngleInDegreesDecimalMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{0:0}}° {{1:0}}&apos; {{2:f{0}}}&quot;.
        /// </summary>
        internal static string AngleInDegreesMinutesSeconds {
            get {
                return ResourceManager.GetString("AngleInDegreesMinutesSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{0:f{0}}}.
        /// </summary>
        internal static string AngleWithNoFormat {
            get {
                return ResourceManager.GetString("AngleWithNoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{0:0}}:{{1:0}}:{{2:f{0}}}.
        /// </summary>
        internal static string HourAngleInCadHoursMinutesSeconds {
            get {
                return ResourceManager.GetString("HourAngleInCadHoursMinutesSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{0:f{0}}}.
        /// </summary>
        internal static string HourAngleInDecimalHours {
            get {
                return ResourceManager.GetString("HourAngleInDecimalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{0:0}}h{{1:f{0}}}m.
        /// </summary>
        internal static string HourAngleInHoursDecimalMinutes {
            get {
                return ResourceManager.GetString("HourAngleInHoursDecimalMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{0:0}}h{{1:0}}m{{2:f{0}}}s.
        /// </summary>
        internal static string HourAngleInHoursMinutesSeconds {
            get {
                return ResourceManager.GetString("HourAngleInHoursMinutesSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{0:f{0}}}.
        /// </summary>
        internal static string HourAngleWithNoFormat {
            get {
                return ResourceManager.GetString("HourAngleWithNoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:00}{1:00}{2:00.0000}{3}.
        /// </summary>
        internal static string HoursAngleInCompactHoursMinutesSeconds {
            get {
                return ResourceManager.GetString("HoursAngleInCompactHoursMinutesSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:00}{1:00}{2:00.0000}{3}.
        /// </summary>
        internal static string LatitudeInCompactDegreesMinutesSeconds {
            get {
                return ResourceManager.GetString("LatitudeInCompactDegreesMinutesSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:000}{1:00}{2:00.0000}{3}.
        /// </summary>
        internal static string LongitudeInCompactDegreesMinutesSeconds {
            get {
                return ResourceManager.GetString("LongitudeInCompactDegreesMinutesSeconds", resourceCulture);
            }
        }
    }
}
